language: node_js
node_js: 9

before_install:
  - openssl aes-256-cbc -K $encrypted_7e9a7f9bc261_key -iv $encrypted_7e9a7f9bc261_iv -in travis-ci/deploy_key.enc -out travis-ci/deploy_key -d
  - chmod 600 "travis-ci/deploy_key"
  - eval "$(ssh-agent -s)"
  - ssh-add "travis-ci/deploy_key"

install: travis-ci/install
script: travis-ci/script
after_success: travis-ci/after_success
