language: node_js
node_js: 9

before_install:
  - openssl aes-256-cbc -K "$encrypted_7e9a7f9bc261_key" -iv "$encrypted_7e9a7f9bc261_iv" -in travis-ci/deploy_key.enc -out travis-ci/deploy_key -d
  - chmod 600 "travis-ci/deploy_key"
  - eval "$(ssh-agent -s)"
  - ssh-add "travis-ci/deploy_key"

install:
  - npm install -g gulp-cli@2.0.0
  - npm install

script:
  - gulp --env=production release

after_success:
  - npm run coveralls
  - travis-ci/after_success
