language: node_js
node_js: 9

before_install:
  - openssl aes-256-cbc -K $encrypted_7e9a7f9bc261_key -iv $encrypted_7e9a7f9bc261_iv -in travis-ci/deploy_key.enc -out travis-ci/deploy_key -d

install:
  - gem install sass -v 3.5.5
  - npm install -g gulp-cli
  - npm install

script:
  - scripts/release

after_success:
  - scripts/deploy
