language: node_js
node_js: 9

before_install: travis-ci/before_install

install:
  - gem install sass -v 3.5.5
  - npm install -g gulp-cli
  - npm install

script:
  - scripts/release

after_success:
  - scripts/deploy
