#!/bin/bash

ENCRYPTED_KEY_VAR="encrypted_${DEPLOY_KEY_TOKEN}_key"
ENCRYPTED_IV_VAR="encrypted_${DEPLOY_KEY_TOKEN}_iv"
ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}

openssl aes-256-cbc -K "$ENCRYPTED_KEY" -iv "$ENCRYPTED_IV" -in travis-ci/deploy_key.enc -out travis-ci/deploy_key -d
chmod 600 "travis-ci/deploy_key"
eval "$(ssh-agent -s)"
ssh-add "travis-ci/deploy_key"
