#!/bin/bash

openssl aes-256-cbc -K $encrypted_7e9a7f9bc261_key -iv $encrypted_7e9a7f9bc261_iv -in deploy_key.enc -out deploy_key -d
chmod 600 "deploy_key"
eval "$(ssh-agent -s)"
ssh-add "deploy_key"
