paths:
  sources:
    directory: "src/app"
    views:
      directory: "src/app/views"
      mainFile: "index.slm"
    stylesheets:
      directory: "src/app/styles"
      mainFile: "application.scss"
    scripts:
      directory: "src/app/scripts"
      mainFile: "application.js"
    assets:
      directory: "src/app/assets"

  build:
    targetDirectory: "build"
    views: "build/app"
    stylesheets: "build/app/stylesheets"
    scripts:
      directory: "build/app/scripts"
      outputFile: "application.js"
    assets: "build/app"

globs:
  allFiles: "**/*"
  allSlmFiles: "**/*.slm"
  allSassFiles: "**/*.s+(a|c)ss"
  allCssFiles: "**/*.css"
  allMinifiedCssFiles: "**/*.min.css"
  allJsFiles: "**/*.js"
  allMinifiedJsFiles: "**/*.min.js"

tasks:
  release:
    - compile-slm
    - lint-sass
    - compile-sass
    - autoprefix-css
    - minify-css
    - lint-js
    - transpile-js
    - minify-js
    - copy-assets
plugins:
  compile-slm:

  lint-sass:
    configFile: "configuration/plugins/gulp-sass-lint/.sass-lint.yml"
    failOnError: true

  compile-sass:
    cacheLocation: "build/tmp/gulp-ruby-sass/.sass-cache"
    emitCompileError: true
    stopOnError: true

  autoprefix-css:
    browsers: "> 1%, last 2 versions, Firefox ESR"

  minify-css:
    suffix: ".min"

  lint-js:
    configFile: "configuration/plugins/gulp-jshint/.jshintrc"
    reporter: "jshint-stylish"
    failOnError: true

  transpile-js:

  minify-js:
    suffix: ".min"
