paths:
  sources:
    stylesheets:
      allFiles: "src/app/styles/**/*.s+(a|c)ss"
      mainSassFile: "src/app/styles/application.scss"

  build:
    stylesheets: "build/app/stylesheets"

globs:
  allCssFiles: "**/*.css"
  allMinifiedCssFiles: "**/*.min.css"

plugins:
  del:
    enabled: true
    directories:
      - "build"

  gulp-sass-lint:
    enabled: true
    configFile: "configuration/plugins/gulp-sass-lint/.sass-lint.yml"
    failOnError: true

  gulp-ruby-sass:
    enabled: true
    cacheLocation: "build/tmp/gulp-ruby-sass/.sass-cache"
    emitCompileError: true
    stopOnError: true

  gulp-autoprefixer:
    enabled: true
    browsers: "> 1%, last 2 versions, Firefox ESR"

  gulp-cssnano:
    enabled: true
    suffix: ".min"
