paths:
  sources:
    stylesheets:
      directory: "src/app/styles"
      mainFile: "application.scss"
    scripts:
      directory: "src/app/scripts"
      mainFile: "application.js"

  build:
    targetDirectory: "build"
    stylesheets: "build/app/stylesheets"
    scripts:
      directory: "build/app/scripts"
      outputFile: "application.js"

globs:
  allSassFiles: "**/*.s+(a|c)ss"
  allCssFiles: "**/*.css"
  allMinifiedCssFiles: "**/*.min.css"
  allJsFiles: "**/*.js"
  allMinifiedJsFiles: "**/*.min.js"

plugins:
  lint-sass:
    enabled: true
    configFile: "configuration/plugins/gulp-sass-lint/.sass-lint.yml"
    failOnError: true

  compile-sass:
    enabled: true
    cacheLocation: "build/tmp/gulp-ruby-sass/.sass-cache"
    emitCompileError: true
    stopOnError: true

  autoprefix-css:
    enabled: true
    browsers: "> 1%, last 2 versions, Firefox ESR"

  minify-css:
    enabled: true
    suffix: ".min"

  lint-js:
    enabled: true
    configFile: "configuration/plugins/gulp-jshint/.jshintrc"
    reporter: "jshint-stylish"
    failOnError: true

  transpile-js:
    enabled: true
